### ISSUE TITLE
서버 배포 및 배포 자동화

### ISSUE THREAD

**Issue by new-pow** [FlytrapHub/RSS-Reader#103]
## **☑️ 진행할 작업**
- AWS에 서버 배포 및 배포 자동화를 합니다.

## **📝TODO**
- [x] AWS EC2 생성 및 배포 후 서브 모듈 업데이트
- [x] RDS 설정 및 배포 후 서브 모듈 업데이트
- [x] BE 서버 배포 자동화

**Comment by new-pow** [comment]
![image](https://github.com/Flytrap-Ware/RSS-Reader/assets/103120173/dc93f0e1-44d8-43b4-afd2-06d1b6244a6b)
