### ISSUE TITLE
모니터링 하는 PC에서 스카우터 장애시 알람 받기,  DB 파티셔닝

### ISSUE THREAD

**Issue by leegyeongwhan** [FlytrapHub/RSS-Reader#165]
## **☑️ 진행할 작업**
- 모니터링 하는 PC에서 스카우터 장애시 알람 받기
- DB 파티셔닝
## **📝TODO**
- [ ] 모니터링 하는 PC에서 EC2 서버의 컴퓨터의 CPU 사용량을 체크하여 80센트가 넘어갈시 스렉으로 알림 받기
- [ ] Post의 description을 파티셔닝 시킨다
- [ ] Subscribe를 파티셔닝 한다.
