### ISSUE TITLE
프로젝트 구조 개선

### ISSUE THREAD

**Issue by new-pow** [FlytrapHub/RSS-Reader#207]
## **☑️ 진행할 작업**
- 프로젝트 구조를 개선합니다.

## **📝TODO**
- [x] 도메인 중심의 패키지 구조 설계
- [x] 시그니처 통일
- [x] 코드 컨벤션 통일
- [x] 각 레이어 의존성 관리
