### ISSUE TITLE
포스트 읽음 여부 기능 추가

### ISSUE THREAD

**Issue by new-pow** [FlytrapHub/RSS-Reader#69]
## **☑️ 진행할 작업**
회원마다 게시글 읽음 여부 기능 추가

## **📝TODO**
- [x] 읽음 여부 저장 테이블 추가
- [x] 게시글 상세 보기 API 구현
- [x] 상세보기시 이벤트 발행하여 읽음여부 추가
- [ ] 읽음여부 삭제 기능 추가
